.vscode/settings.json
src/Pages/Timer.js

Basics for stopwatch

---

.vscode/settings.json
src/Pages/Timer.js

CountDown with Error

---

src/Components/Order/AllStudentList.js
src/Components/Order/StudentOrder.js
src/Pages/Order.js
src/apollo.js

order divideRight->List

---

src/Pages/Timer.js

add PAUSE and RESET in Timer

---

src/Components/Timer/Btn.js
src/Pages/Timer.js

TIMER: Add TimeRecords on LocalStorage

Add TimeRecords on LocalStorage

---

src/Components/Timer/TimeDisplay.js
src/Pages/Timer.js

1. Add CountdownTimer
2. Add box-shadow in TimeDisplay

Timer: Add CountdownTimer / CSS

---

src/Pages/EditAccount.js

delete console.log, delete EditAccount EditDDay

---

README.md

feature-attend-layout

---

public/index.html

connect google analytics

---

src/Pages/Lunchmenu.js

136 development refactoring lunchmenu comment

---

src/Pages/PageLink.js

refactoring start

---

src/Pages/Lunchmenu.js

133 development refactoring lunchmenu

---

src/Pages/Draw.js

132 development refactoring draw

---

src/apollo.js

131 development refactoring apollojs

---

src/Components/Lunchmenu/AllergyItem.js
src/Components/Lunchmenu/Date.js
src/Components/Lunchmenu/Popup/SeeAllergy.js
src/Components/Lunchmenu/SchoolNameForm.js
src/Components/Lunchmenu/SearchSchool.js
src/Pages/Lunchmenu.js

본격적인 리팩토링에 앞서 간단히 필요없는 컴포넌트, 콘솔, 주석을삭제했습니다:)
#164 
Closes #164

delete unnecessary content

---

src/Components/Lunchmenu/BasicInfo.js
src/Components/Lunchmenu/LunchmenuBtn.js
src/Components/Lunchmenu/LunchmenuInfo.js
src/Components/Lunchmenu/SearchContainer.js
src/Components/Lunchmenu/SearchDate.js
src/Pages/Lunchmenu.js

컴포넌트가 분리되지 않아 Pages/Lunchmenu의 코드가 너무 길었습니다. 그래서 각각의 특징에 따라 컴포넌트를 나누었습니다:)
아래 이슈 참고
#166 
Fixes #166

166 refactoring lunchmenu components separate

---

src/Components/Lunchmenu/LunchmenuBtn.js
src/Components/Lunchmenu/LunchmenuInfo.js
src/Components/Lunchmenu/SearchContainer.js
src/Components/Lunchmenu/SearchDate.js
src/Components/Lunchmenu/SearchSchool.js
src/Pages/Lunchmenu.js

refactoring-lunchmenu-state

---

src/Components/Lunchmenu/AllergyItem.tsx
src/Components/Lunchmenu/BasicInfo.tsx
src/Components/Lunchmenu/LunchmenuBtn.tsx
src/Components/Lunchmenu/LunchmenuInfo.tsx
src/Components/Lunchmenu/Popup/SearchSchool.tsx
src/Components/Lunchmenu/SearchContainer.tsx
src/Components/Lunchmenu/SearchDate.tsx
src/Pages/Lunchmenu.tsx
src/apollo.js

#188 
Lunchmenu에서 사용된 함수를 리팩토링하였습니다.
복잡한 코드를 최대한 가독성 좋게 만들기 위해 고민했으며 중복되는 코드를 줄이도록 했습니다:)

188 refactoring lunchmenu function variable

---

src/App.js
src/Components/Qrcode/QrcodeInput.js
src/Components/Qrcode/Qrcontext.js
src/Components/Qrcode/Qrmake.js
src/Components/Qrcode/Qrname.js
src/Components/Qrcode/Qroptionbtn.js
src/Components/Qrcode/Qrresult.js
src/Pages/Qrcode.js
src/Pages/QrcodeResult.js
src/Pages/QrcodeStorage.js
src/routes.js

1. 결과페이지 분할 (생성에서 state값으로 url 넘기기, 보관함에서 state값으로 url 넘기기 완료, index값으로 쿼리 불러오기 추가 중)
2. 제목 글자수 제한 10글자로 지정
3. 체크 칸 선택시 칸 배경 색 변경 및 테두리선 추가 
4. 안내 메시지 아직 수정 중

결과페이지 분할(전달 3가지 중 2가지 완료)/ 제목 글자수 제한/체크 칸 모양 변경

---

src/Components/Qrcode/Qrmake.js
src/Components/Qrcode/Qrname.js
src/Components/Qrcode/Qrresult.js
src/Pages/Qrcode.js

qrcode url 을 localStorage에 저장하여 popup창에 넘김 수정

qr popup 수정

---

src/Components/Qrcode/Qrmake.js
src/Components/Qrcode/Qrresult.js
src/Pages/Qrcode.js

popup창 뜨는 거 수정
me 없는 경우 로그인 안내 
결과 화면에서 링크 연결 추가 
저장 완료 안내 메세지 아직 안 됨. 
기타 정렬 아직 못 함.

Feature popup qrcode error
